# Generated by Django 5.2.2 on 2025-08-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room'), ('studio', 'Studio Apartment'), ('apartment', 'Full Apartment'), ('house', 'House')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('area_m2', models.IntegerField(default=25)),
                ('beds', models.IntegerField(default=1)),
                ('baths', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
