# Generated by Django 5.2.2 on 2025-08-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('started', '0005_client_owner_alter_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='company_name',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('chat_access', 'Chat Access'), ('room_unlock', 'Room Unlock')], default='room_unlock', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='started.room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='started.room'),
        ),
        migrations.CreateModel(
            name='RoomAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='started.client')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='started.payment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='started.room')),
            ],
            options={
                'unique_together': {('client', 'room')},
            },
        ),
    ]
