# Generated by Django 5.2.2 on 2025-08-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('started', '0007_alter_message_options_and_more'),
    ]

    # ClientPayment was already included in 0007.  Keep this migration as a
    # no-op so a fresh database does not attempt to create the table twice.
    operations = []
