# Generated by Django 5.2.2 on 2025-09-01 15:50

from django.db import migrations, models
from django.db.utils import IntegrityError


class Migration(migrations.Migration):

    dependencies = [
        ('started', '0008_add_clientpayment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_pin',
            field=models.CharField(blank=True, max_length=6, null=True)
            ),
    ]

    def apply(self, project_state, schema_editor, collect_sql=False):
        try:
            return super().apply(project_state, schema_editor, collect_sql)
        except IntegrityError as e:
            raise IntegrityError(f"Migration failed: {e}")