# Generated by Django 4.2.30 on 2026-09-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('started', '0013_fix_message_conversation'),
        ('started', '0017_alter_room_latitude_alter_room_longitude_and_more'),
    ]

    operations = [
    ]
